export const INVALID_AUDIO_FILE_ERROR_CODE = 'INVALID_AUDIO_FILE';
export const INVALID_CHAT_FILE_ERROR_CODE = 'INVALID_CHAT_FILE';
export const INVALID_AVATAR_FILE_ERROR_CODE = 'INVALID_AVATAR_FILE';
