export const SUPABASE_STORAGE_AVATAR_BUCKET =
    process.env.SUPABASE_STORAGE_AVATAR_BUCKET!;
export const SUPABASE_STORAGE_SIGNED_URL_EXPIRES_IN = Number(
    process.env.SUPABASE_STORAGE_SIGNED_URL_EXPIRES_IN
);
